CREATE TABLE incident (
  "Incident_ID" INTEGER,
  "ResponderUnit_ID" INTEGER,
  "RunNumber" VARCHAR(20),
  "AlarmLevel_ID" INTEGER,
  "MutualAid_ID" INTEGER,
  "FMARespComp" VARCHAR(3),
  "FireBlock" VARCHAR(6),
  "NeighborAssoc" VARCHAR(18),
  "CensusTract" VARCHAR(6),
  "Quad" VARCHAR(2),
  "StreetName" VARCHAR(30),
  "StreetType" VARCHAR(4),
  "Quad2" VARCHAR(2),
  "StreetName2" VARCHAR(30),
  "StreetType2" VARCHAR(4),
  "County" VARCHAR(30),
  "City" VARCHAR(30),
  "State" VARCHAR(2),
  "Zip" VARCHAR(9),
  "IncDate" DATE,
  "TypeNatureCode_ID" INTEGER,
  "IncSitFoundPrm_ID" INTEGER
);
